#!/usr/bin/python
import os

data_dir = "./DB"
post_file = os.path.join(data_dir, "posts.txt")
upload_dir = os.path.join(data_dir, "uploads")
if not os.path.exists(data_dir):
    os.makedirs(data_dir)
if not os.path.exists(upload_dir):
    os.makedirs(upload_dir)

print("Content-Type: text/html")
print("")
print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head>")
print("    <meta charset='UTF-8'>")
print("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
print("    <title>My Website</title>")
print("</head>")
print("<body>")
print("    <header>")
print("        <h1>Welcome to My Website</h1>")
print("    </header>")
print("    <main>")
print("        <section>")
print("            <h2>Create a New Post</h2>")
print("            <form action='/cgi/post.php' method='post' enctype='multipart/form-data' onsubmit='submitPost(event)'>")
print("                <label for='title'>Title:</label>")
print("                <input type='text' id='title' name='title' required><br><br>")
print("                <label for='content'>Content:</label>")
print("                <textarea id='content' name='content' rows='4' cols='50' required></textarea><br><br>")
print("                <label for='image'>Image:</label>")
print("                <input type='file' id='image' name='image' accept='image/*'><br><br>")
print("                <input type='submit' value='Submit'>")
print("            </form>")
print("        </section>")
print("        <section>")
print("            <h2>Discussion Topics</h2>")
print("            <ul>")
if os.path.exists(post_file):
    with open(post_file, 'r') as file:
        lines = file.readlines()
        lines.reverse()
        for line in lines:
            title, content, post_id, cookie = line.strip().split('\t')
            print("<p>Title: {}</p>".format(title))
            print("<p>Content: {}</p>".format(content))
            image_path = os.path.join(upload_dir, "image_" + post_id + ".jpg")
            if os.path.exists(image_path):
                print('<img src="/DB/uploads/image_{}.jpg" alt="Image" width="200">'.format(post_id))
            print("<button id='deleteButton{}' onclick='deletePost({})'>Delete</button>".format(post_id, post_id))
            print("")
print("            </ul>")
print("        </section>")
print("    </main>")
print("    <footer>")
print("        <p>&copy; 2023 My Website. All rights reserved.</p>")
print("    </footer>")
print("</body>")
print('<script>')
print("function submitPost(event) {")
print("    event.preventDefault();")
print("    const formData = new FormData();")
print("    formData.append('title', document.getElementById('title').value);")
print("    formData.append('content', document.getElementById('content').value);")
print("    formData.append('image', document.getElementById('image').files[0]);")
print("    fetch('/cgi/post.php', {")
print("        method: 'POST',")
print("        body: formData")
print("    })")
print("    .then(response => {")
print("        if (response.ok) {")
print("            location.reload();")
print("        } else {")
print("            throw new Error('POST request error!');")
print("        }")
print("    })")
print("    .catch(error => {")
print("        console.error('Error:', error);")
print("    });")
print("}")
print("")
print("function deletePost(post_id) {")
print("    if (confirm(\"Delete this post?\")) {")
print("        fetch(`/cgi/delete.py?post_id=${post_id}`, {")
print("            method: 'DELETE'")
print("        })")
print("        .then(response => {")
print("            if (response.ok) {")
print("                location.reload();")
print("            } else {")
print("                throw new Error('DELETE request error!');")
print("            }")
print("        })")
print("        .catch(error => {")
print("            console.error('Error:', error);")
print("        });")
print("    }")
print("}")
print('</script>')
print("</html>")
